Mathematical and Statistical Functions

`ndarray` Methods

`mean()`

Computes the Mean of all the elements in the `ndarray`, regardless of the Shape.

`min()`

Computes the Minimum element.

`max()`

Computes the Maximum element.

`sum()`

Gives the Sum of all the elements in the Array.

`prod()`

Gives the Product of all the elements in the Array.

`std()`

Computes the Standard Deviation.

`var()`

Computes the Variance.

In [ ]:
import numpy as np

a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print("Array:\n", a)

for func in (a.mean, a.min, a.max, a.sum, a.prod, a.std, a.var):
  print(func.__name__, "=", func())

Array:
 [[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667
min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


These functions also accept an optional argument `axis`, which lets the operation be performed on the elements along the given Axis.

In [ ]:
a = np.arange(24).reshape(2,3,4)

print("Sum across Matrices:\n", a.sum(axis = 0))
print("Sum across Rows:\n", a.sum(axis = 1))
print("Sum across Matrices and Cols:\n", a.sum(axis = (0, 2)))

Sum across Matrices:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Sum across Rows:
 [[12 15 18 21]
 [48 51 54 57]]
Sum across Matrices and Cols:
 [ 60  92 124]


Universal Functions `ufunc`

NumPy provides fast element-wise functions called Universal Functions or `ufunc`. They are vectorized wrappers of simple functions. For example, `square()` returns a new `ndarray` whcih is a copy of the original, except each element is squared.

`np.square()`

Returns new `ndarray` with each element Squared.

`np.abs()`

Each element in the new `ndarray` is of its Absolute Value.

`np.sqrt()`

Each element is Square Rooted.

`np.exp()`

Calculates Exponential of each element.

`np.log()`

Computes the Natural Logarithm of each element. It is opposite of `np.exp()`.

`np.sign()`

Returns element-wise indication of the Sign of the number.

`np.ceil()`

Gives the Ceiling of the elements.

`np.modf()`

Separates the Fractional and Integral parts of the elements.

`np.isnan()`

Tests element-wise for NaN value and returns a Boolean Array (Array with values as Boolean, True or False)


`np.cos()`

Calculates Cosine of an Array of angles given as radians.

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

print("Original Array:\n", a)
print(a)
for func in (np.square, np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original Array:
 [[-2.5  3.1  7. ]
 [10.  11.  12. ]]
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 square
[[  6.25   9.61  49.  ]
 [100.   121.   144.  ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


<ipython-input-74-92fff1085eff>:8: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
<ipython-input-74-92fff1085eff>:8: RuntimeWarning: invalid value encountered in log
  print(func(a))


Note that there are two warnings generated because `np.sqrt()` and np.log() are undefined for negative numbers.

Binary `ufunc`

They apply element-wise on two `ndarrays`. Broadcasting rules are applied if the Arrays do not have the same Shape.

In [ ]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
print("Array a\n", a)
print("Array b\n", b)

for func in (np.add, np.greater, np.maximum, np.copysign):
    print("\n", func.__name__)
    print(func(a, b))

Array a
 [ 1 -2  3  4]
Array b
 [ 2  8 -1  7]

 add
[ 3  6  2 11]

 greater
[False False  True False]

 maximum
[2 8 3 7]

 copysign
[ 1.  2. -3.  4.]




---


Indexing and Slicing Arrays

1-Dimensional Arrays can be accessed like the regular Python arrays.

In [ ]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
print("Array a:\n", a, "\n")

print("4th element:", a[3])
print("3rd to 5th elements:", a[2:5])

Array a:
 [ 1  5  3 19 13  7  3] 

4th element: 19
3rd to 5th elements: [ 3 19 13]


We can also modify the elements.

In [ ]:
a[3] = 999
a[2:5] = [997, 998, 999]

print("New Array a:\n", a)

New Array a:
 [  1   5 997 998 999   7   3]


Difference from regular Python Arrays

Contrary to Python lists, if we assign a single value to an `ndarray` slice, its copied across the whole slice due to Broadcasting.

In [ ]:
a[2:5] = -1
a

array([ 1,  5, -1, -1, -1,  7,  3])

We cannot grow or shink the `ndarray` using slices. We cannot delete elements. Most importantly, `ndarray` slices are pointing to the same data. If we create a slice and modify it, it will modify the original value in the Array as well.

In [ ]:
a_slice = a[2:6]
a_slice[1] = 1000
a

array([   1,    5,   -1, 1000,   -1,    7,    3])

Deep Copy

We can use the `copy()` method which will leave the original Array untouched if we modify the slices on the copy. This is called creating a Deep Copy.

In [ ]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a

array([   1,    5,   -1, 1000,   -1,    7,    3])

Multi-Dimensional Arrays

They can be accessed in a similar way, by providing an index or a slice for each axis separated by commas.

In [ ]:
a = np.arange(48).reshape(4, 12)
print("Array a:\n", a)

print("\nElement in Row 1 and Col 2:", a[1, 2])
print("\nElements in Row 1 and All Columns:", a[1, :])
print("\nElements in Row 1 and All Columns as a 2-D Array:", a[1:2, :])

Array a:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]]

Element in Row 1 and Col 2: 14

Elements in Row 1 and All Columns: [12 13 14 15 16 17 18 19 20 21 22 23]

Elements in Row 1 and All Columns as a 2-D Array: [[12 13 14 15 16 17 18 19 20 21 22 23]]


Fancy Indexing

We can specify a list of indices that we are interested in.

In [ ]:
# Rows 0 and 2, Cols 2 to 4
a[(0, 2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

Higher Dimensions

In [ ]:
b = a.reshape(4, 2, 6)

# Element at Matrix 2, Row 1 and Col 4
b[2, 1, 4]

34

If we omit coordinates for some Axes, then all elements are returned

In [ ]:
b[2, 1] # Matrix 2, Row 1 and All Cols, equivalent to b[2, 1, :]

array([30, 31, 32, 33, 34, 35])

Ellipsis `...`

We can write an Ellipsis to ask that all non-specified Axes be included

In [ ]:
b[2, ...] # Equivalent to b[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])



---


Iterating Arrays

It is similar to iterating over regular Python lists. Note that iterating over Multi-Dimensional Arrays is done with respect to first Axis.

In [ ]:
c = np.arange(24).reshape(2, 3, 4) # We take a 3-D Array (composed of two 2-D Matrices)
print("Array c:\n", c)
print("\n")

for m in c:
  print("Item:")
  print(m)

print("\n")

for i in range(len(c)):
  print("Item:")
  print(c[i])

print("\n")

for i in c.flat:
  print("Item:", i)

Array c:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Item: 0
Item: 1
Item: 2
Item: 3
Item: 4
Item: 5
Item: 6
Item: 7
Item: 8
Item: 9
Item: 10
Item: 11
Item: 12
Item: 13
Item: 14
Item: 15
Item: 16
Item: 17
Item: 18
Item: 19
Item: 20
Item: 21
Item: 22
Item: 23




---


Stacking Arrays

It can be useful to Stack different Arrays.

`vstack()`

We can use `vstack()` to vertically Stack Arrays. They must have same number of Columns.

In [ ]:
q1 = np.full((3, 4), 1.0)
q2 = np.full((4, 4), 2.0)
q3 = np.full((3, 4), 3.0)
print("Array q1\n", q1)
print("Array q2\n", q2)
print("Array q3\n", q3)
print("\n")

q4 = np.vstack((q1, q2, q3))
q4

Array q1
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array q2
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
Array q3
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]




array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

`hstack()`

We can use `hstack()` to vertically Stack Arrays. They must have same number of Rows.

In [ ]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

`concatenate()`

It Stacks Arrays along any given existing Axis.

In [ ]:
q6 = np.concatenate((q1, q2, q3), axis = 0) # Equivalent to vstack
q6
# hstack is equivalent to calling concatenate with Axis = 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

`stack()`

It Stacks Arrays along a new Axis. Note that all Arrays have to have the same Shape.

In [ ]:
q7 = np.stack((q1, q3))
q7

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])



---


Splitting Arrays

It is the opposite of Stacking.

`vsplit()`

Splits into equal parts vertically.

In [ ]:
r = np.arange(24).reshape(6, 4)
print("Array r:", r)
print("\n")

r1, r2, r3 = np.vsplit(r, 3)
r1, r2, r3

Array r: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]




(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]))

`hsplit()`

Splits an Array equally horizontally.

In [ ]:
r4, r5 = np.hsplit(r, 2)
r4, r5

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]]))

`split()`

Splits an Array along any given Axis. `vsplit()` is equivalent to `split()` with Axis = 0 and `hsplit()` is equivalent to `split()` with Axis = 1.



---


Transposing Arrays

`transpose()` method create a new view of an `ndarray`'s data, with Axes permuted in the given order. By default, `transpose()` reverses the order of the dimensions.

In [ ]:
t = np.arange(24).reshape(4,2,3)
print("Array t:\n", t)
print("\n")

t1 = t.transpose((1, 2, 0)) # Axes (0, 1, 2) become (1, 2, 0)
t1

Array t:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]




array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

There is also a convenient function to swap any two Axes called `swapaxes()`.

In [ ]:
t3 = t.swapaxes(0, 1) # Axes (0, 1, 2) become (1, 0, 2)
t3

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])