NumPy

A Python library for scientific computing, centered around N-Dimensional Arrays.

In [ ]:
import numpy as np

a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Axis

In NumPy, each Dimension is called Axis.

Rank

Number of Axes = Rank

In [ ]:
a.ndim

2

Shape

An Array's lists of Axes length is called Shape of the Array.

In [ ]:
a.shape

(3, 4)

Size

Size of an Array is total number of elements, which is the product of all Axis lengths.

In [ ]:
a.size

12

NumPy Array Datatype

NumPy Arrays have the Datatype `ndarray`. They are effecient, in part because all their elements must have the same Datatype (usually `int` or `float`).

In [ ]:
print(a.dtype)
type(a)

float64


numpy.ndarray



---


Methods to Create Arrays

`np.zeros()`

Array containing any number of zeros.

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

`np.ones()`

Array containing any number of ones.

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`np.full()`

Array of a given shape initialized with given values.

In [ ]:
np.full((3, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

`np.empty()`

Uninialized Array with random values.

In [ ]:
np.empty((2, 3))

array([[4.76181362e-310, 0.00000000e+000, 2.14321575e-312],
       [3.01694968e+174, 6.01334504e-154, 4.63366149e+228]])

`np.array()`

Array using regular Python lists.

In [ ]:
np.array([[1, 2, 3, 4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

`np.arange()`

Similar to Python's range() function, also works with `float` but then exact number of elements is not predictable.

In [ ]:
np.arange(1.0, 5.0)

array([1., 2., 3., 4.])

`np.linspace()`

Array containing specific number of points evenly distributed between two values, prefered when working with `float`.

In [ ]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

`np.random.rand()`

Array of random values over normal distribution between 0 and 1 using NumPy's `random` module.

In [ ]:
np.random.rand(3, 4)

array([[0.26764708, 0.02826441, 0.48567653, 0.68902607],
       [0.57381352, 0.97159152, 0.81810451, 0.21963394],
       [0.37454658, 0.36939692, 0.8913614 , 0.49618736]])

`np.random.randn()`

Array of random floats from univariate normal distribution (Gaussian distribution) with mean = 0 and variance = 1 using NumPy's `random` module.

In [ ]:
np.random.randn(3, 4)

array([[ 0.78864505, -0.97236768,  0.66102874,  0.40435894],
       [ 0.94356429, -1.22387237, -0.78787809, -0.79448209],
       [ 0.46421099, -0.34509875,  0.02054196,  1.47559862]])

`np.fromfunction()`

Array using values from a function.

In [ ]:
# To create values
def my_function(z, y, x):
  return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])



---


Reshaping an Array

One way is manually changing shape attributes of an Array such that Array's size remains the same.

In [ ]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


`reshape()`

Using `reshape()` function to return a new Array pointing at the same data. If we modify elements of new Array, the original one will also be modified.

In [ ]:
g2 = g.reshape(4, 6)
print(g2)
print("Rank:", g2.ndim)

g2[1, 2] = 999
print(g2)
g

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2
[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]


array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [999,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

`ravel()`

`ravel()` function returns a new 1-Dimensional Array pointing to the same data.

In [ ]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])



---


Elementwise Operations

All usual Arithmetic Operators (`+`, `-`, `*`, etc.) can be used with `ndarray` datatype. They are applied elementwise. Note that multiplication here is not same as matrix multiplication since this is being done elementwise.

In [ ]:
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a + b = [19 27 35 43]
a - b = [ 9 19 29 39]
a * b = [70 92 96 82]


Comparison Operators (`>`, `<`, etc.) are also applied elementwise on `ndarray` datatype.

In [ ]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])



---


Broadcasting

In general, NumPy excepts Arrays of the same shape when performing operations. If thats not the case, Broadcasting is applied. Smaller Array is Broadcast across the larger Array so that they have compatible Shapes. There are also cases where Broadcasting is a bad idea because it leads to inefficient use of memory.

In [ ]:
h = np.arange(5).reshape(1, 1, 5)
print("Array h:\n", h)
print("\n")

h + [10, 20, 30, 40, 50]  # Same as: h + [[[10, 20, 30, 40, 50]]]

Array h:
 [[[0 1 2 3 4]]]




array([[[10, 21, 32, 43, 54]]])

General Broadcasting Rules

When operating on two Arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., right-most) Dimension and works its way left. Two Dimensions are compatible when -

1. They are equal
2. One of them is 1 (Broadcasting is applied here)

If these conditions are not, an error is thrown that operands could not be Broadcasted together.

In [ ]:
k = np.arange(6).reshape(2, 3)
print("Array k:\n", k)
print("\n")

k + 1000  # Same as: k + [[1000, 1000, 1000], [1000, 1000, 1000]]

Array k:
 [[0 1 2]
 [3 4 5]]




array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

Input Arrays do not need to have same number of Dimensions. The resulting Array will have the same number of Dimensions as the input Array with greatest number of Dimensions, where size of each Dimension is the largest of the corresponding Dimensions among the input Arrays.

Upcasting

When combining two Arrays with elements of different datatypes, NumPy will Upcast to a type capable of handling all possible values (regardless of what the actual values are).

In [ ]:
k1 = np.arange(0, 5)
print("Array k1:\n", k1)
print("\n")

k2 = k1 + 1.5
k2

Array k1:
 [0 1 2 3 4]




array([1.5, 2.5, 3.5, 4.5, 5.5])